### ISSUE TITLE
Website not reachable SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by DunklerPhoenix** [rclone/filterdemo#1]
Heho
The filterdemo is offline at the moment due to an ssl error.

**Comment by wwarriner** [comment]
This site sounds great, but I'm unable to use it.

I'm getting similar, but the error is `SSL_ERROR_INTERNAL_ERROR_ALERT`.

**Comment by ncw** [comment]
I have fixed the site - sorry!
